### ISSUE TITLE
Chm files that have a '&' in their summary index (e. g. 6.14.4 Keybord & Mouse), cannot load ==> exception "Out of range".

### ISSUE THREAD

**Issue by infologick** [serbod/lazhelp#1]
Attached to this text, are the fix to this bug that was in the **"function FixEscapedHTML(AText: string): string;"** procedure, and the user.chm help file that caused the lhelp crash 

_(My development configuration: Ubuntu 18.04 + Laz. 1.8.5 + FPC 3.0.5, but I don't think it has any importance in this coreection, since your function is in pure Free Pascal independent of the Windows or Linux APIs, or of the Delphi VCL, ...)._

[ChmSpecialParser.zip](https://github.com/serbod/lazhelp/files/3301006/ChmSpecialParser.zip)

**Comment by serbod** [comment]
Fixed! Thank you very much!

**Comment by infologick** [comment]
>
> Fixed! Thank you very much!
>

It is especially me who thanks you: your software is very useful to me.

-- 
Regards,
Éric Moutié.
